###############################################################################
#        Copyright (C) 2020        Sebastian Francisco Colomar Bauza          #
#        Copyright (C) 2020        Alejandro Colomar Andr√©s                   #
#        SPDX-License-Identifier:  GPL-2.0-only                               #
###############################################################################

version: "2"

services:

    cam:
        image: alejandrocolomar/rob_cam:cam
        devices:
        -   "/dev/video0:/dev/video0"
        environment:
        -   CAMERA_IDX=0
        -   DELAY_US=10000
        -   ROB_ADDR=rob
        -   ROB_PORT=13100
        depends_on:
            - rob
        restart: always

    rob:
        image: alejandrocolomar/rob_cam:rob
        environment:
        -   DELAY_LOGIN=1000000
        -   DELAY_US=100000
        -   ROB_CAMS_MAX=1
        -   ROB_PORT=13100
        -   ROBOT_ADDR=robot
        -   ROBOT_PASSWD=
        -   ROBOT_STATUS_FNAME=status.log
#        -   ROBOT_TYPE=kwr
        -   ROBOT_TYPE=ur
        -   ROBOT_USER=
        depends_on:
        -   robot
        restart: always

    robot:
        image: alejandrocolomar/rob_cam:ur-sim
        restart: always

################################################################################
#sudo docker-compose up -d                                                     ;
#sudo docker-compose down                                                      ;
################################################################################
